
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATRIBUT CLASS EQUAL ID LPAREN NEWLINE RPAREN SPACE TAB TAG TEXTOlinha :  identacao corpo NEWLINEidentacao :  TAB identacao\n                    | SPACE identacao\n                    | \n    corpo :  tag\n                | tag SPACE TEXTO\n                | tag EQUAL SPACE TEXTO\n    tag :    TAG\n                | ID\n                | ID tag\n                | CLASS\n                | CLASS tag\n                | tag LPAREN atributos RPAREN\n    atributos :  ATRIBUT\n                    | ATRIBUT atributos\n    '
    
_lr_action_items = {'TAB':([0,3,4,],[3,3,3,]),'SPACE':([0,3,4,6,7,8,9,14,16,17,23,],[4,4,4,13,-8,-9,-11,19,-10,-12,-13,]),'TAG':([0,2,3,4,8,9,10,11,],[-4,7,-4,-4,7,7,-2,-3,]),'ID':([0,2,3,4,8,9,10,11,],[-4,8,-4,-4,8,8,-2,-3,]),'CLASS':([0,2,3,4,8,9,10,11,],[-4,9,-4,-4,9,9,-2,-3,]),'$end':([1,12,],[0,-1,]),'NEWLINE':([5,6,7,8,9,16,17,18,22,23,],[12,-5,-8,-9,-11,-10,-12,-6,-7,-13,]),'EQUAL':([6,7,8,9,16,17,23,],[14,-8,-9,-11,-10,-12,-13,]),'LPAREN':([6,7,8,9,16,17,23,],[15,-8,-9,-11,15,15,-13,]),'TEXTO':([13,19,],[18,22,]),'ATRIBUT':([15,21,],[21,21,]),'RPAREN':([20,21,24,],[23,-14,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'linha':([0,],[1,]),'identacao':([0,3,4,],[2,10,11,]),'corpo':([2,],[5,]),'tag':([2,8,9,],[6,16,17,]),'atributos':([15,21,],[20,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> linha","S'",1,None,None,None),
  ('linha -> identacao corpo NEWLINE','linha',3,'p_linha','yac_pug.py',5),
  ('identacao -> TAB identacao','identacao',2,'p_identacao','yac_pug.py',10),
  ('identacao -> SPACE identacao','identacao',2,'p_identacao','yac_pug.py',11),
  ('identacao -> <empty>','identacao',0,'p_identacao','yac_pug.py',12),
  ('corpo -> tag','corpo',1,'p_corpo','yac_pug.py',22),
  ('corpo -> tag SPACE TEXTO','corpo',3,'p_corpo','yac_pug.py',23),
  ('corpo -> tag EQUAL SPACE TEXTO','corpo',4,'p_corpo','yac_pug.py',24),
  ('tag -> TAG','tag',1,'p_tag','yac_pug.py',29),
  ('tag -> ID','tag',1,'p_tag','yac_pug.py',30),
  ('tag -> ID tag','tag',2,'p_tag','yac_pug.py',31),
  ('tag -> CLASS','tag',1,'p_tag','yac_pug.py',32),
  ('tag -> CLASS tag','tag',2,'p_tag','yac_pug.py',33),
  ('tag -> tag LPAREN atributos RPAREN','tag',4,'p_tag','yac_pug.py',34),
  ('atributos -> ATRIBUT','atributos',1,'p_atributos','yac_pug.py',39),
  ('atributos -> ATRIBUT atributos','atributos',2,'p_atributos','yac_pug.py',40),
]
